# Generated by Django 4.2.1 on 2023-07-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=20)),
            ],
            options={
                "db_table": "doctors",
            },
        ),
    ]
