# Generated by Django 4.2.1 on 2023-07-19 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_app", "0002_doctor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("address", models.CharField(max_length=300)),
                ("phone", models.CharField(max_length=20)),
            ],
        ),
    ]
