# Generated by Django 4.2.1 on 2023-07-19 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("all_app", "0003_patient"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="patient",
            table="patients",
        ),
    ]
