# Generated by Django 4.2.1 on 2023-07-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_app", "0005_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department_name", models.CharField(max_length=100)),
                ("department_description", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "department",
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(null=True)),
                ("doctor_name", models.ManyToManyField(to="all_app.doctor")),
                ("patient_name", models.ManyToManyField(to="all_app.patient")),
            ],
            options={
                "db_table": "appointment",
            },
        ),
    ]
