# Generated by Django 4.2.1 on 2023-07-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("all_app", "0006_department_appointment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Appointment",
        ),
    ]
