# Generated by Django 4.2.1 on 2023-07-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("all_app", "0007_delete_appointment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(null=True)),
                ("doctor_name", models.ManyToManyField(to="all_app.doctor")),
                ("patient_name", models.ManyToManyField(to="all_app.patient")),
            ],
            options={
                "db_table": "appointment",
            },
        ),
    ]
